name: latexmk-workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: texlive/texlive
          run: |
           latexmk -pdf -auxdir=/tmp/latexmk
